# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yousefs
# "service" is the name of this project. This will also be added to your AWS resource names.
service: swingNotes-apiExempel


provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
 

 
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [NotesTable, Arn]
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    NOTES_TABLE: notes-table
    USERS_TABLE: notes-table-user
    JWT_SECRET: your-jwt-secret

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
  getNotes:
    handler: functions/Notes/getNotes/getNotes.handler
    events:
      - httpApi:
          path: /notes
          method: get
  addNotes:
    handler: functions/Notes/addNotes/addNotes.handler
    events:
      - httpApi:
          path: /notes
          method: post
  updateNotes:
    handler: functions/Notes/updateNotes/updateNotes.handler
    events:
      - httpApi:
          path: /notes
          method: put
  deleteNotes:
    handler: functions/Notes/deleteNotes/deleteNotes.handler
    events:
      - httpApi:
          path: /notes
          method: delete
  signup:
    handler: functions/User/signup/signup.handler
    events:
      - httpApi:
          path: /user/signup
          method: post
  login:
    handler: functions/User/login/login.handler
    events:
      - httpApi:
          path: /user/login
          method: post

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-table-user
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: username-index
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL